all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: vagrant
    ansible_become: true
    security_mode: plaintext
  hosts:
    node0:
      ansible_port: 2222
      ansible_host: 127.0.0.1
    node1:
      ansible_port: 2200
      ansible_host: 127.0.0.1
    node2:
      ansible_port: 2202
      ansible_host: 127.0.0.1
    node3:
      ansible_port: 2201
      ansible_host: 127.0.0.1
preflight:
  hosts:
    node0:
    node1:
    node2:
    node3:
ssl_CA:
  hosts:
    node0:
zookeeper:
  hosts:
    node0:
    node1:
    node2:
broker:
  hosts:
    node0:
      kafka:
        broker:
          id: 1
    node1:
      kafka:
        broker:
          id: 2
    node2:
      kafka:
        broker:
          id: 3
schema-registry:
  hosts:
    node0:
control-center:
  hosts:
    node3:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: node0:8083
connect-distributed:
  hosts:
    node0:
kafka-rest:
  hosts:
    node0:
ksql:
  hosts:
    node1:
tools:
  hosts:
    node1:
